# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.contact_response import ContactResponse
from ..core.pydantic_utilities import parse_obj_as
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..core.jsonable_encoder import jsonable_encoder
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ContactsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create(
        self,
        *,
        phone_number: str,
        first_name: typing.Optional[str] = OMIT,
        last_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ContactResponse:
        """
        Creates a new Contact object.

        Parameters
        ----------
        phone_number : str
            The contact's phone number in E.164 format.

        first_name : typing.Optional[str]
            The contact's first name.

        last_name : typing.Optional[str]
            The contact's last name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ContactResponse
            Contact

        Examples
        --------
        from surge import Splitit

        client = Splitit(
            surge_account="YOUR_SURGE_ACCOUNT",
            token="YOUR_TOKEN",
        )
        client.contacts.create(
            first_name="Dominic",
            last_name="Toretto",
            phone_number="+18015551234",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "contacts",
            method="POST",
            json={
                "first_name": first_name,
                "last_name": last_name,
                "phone_number": phone_number,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ContactResponse,
                    parse_obj_as(
                        type_=ContactResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def show(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ContactResponse:
        """
        Retrieves a Contact object.

        Parameters
        ----------
        id : str


        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ContactResponse
            Contact

        Examples
        --------
        from surge import Splitit

        client = Splitit(
            surge_account="YOUR_SURGE_ACCOUNT",
            token="YOUR_TOKEN",
        )
        client.contacts.show(
            id="ctc_01j9dy8mdzfn3r0e8x1tbdrdrf",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"contacts/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ContactResponse,
                    parse_obj_as(
                        type_=ContactResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def update(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ContactResponse:
        """
        Updates the specified contact by setting the values of the parameters passed. Any parameters not provided will be left unchanged.

        Parameters
        ----------
        id : str


        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ContactResponse
            Contact

        Examples
        --------
        from surge import Splitit

        client = Splitit(
            surge_account="YOUR_SURGE_ACCOUNT",
            token="YOUR_TOKEN",
        )
        client.contacts.update(
            id="ctc_01j9dy8mdzfn3r0e8x1tbdrdrf",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"contacts/{jsonable_encoder(id)}",
            method="PUT",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ContactResponse,
                    parse_obj_as(
                        type_=ContactResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncContactsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create(
        self,
        *,
        phone_number: str,
        first_name: typing.Optional[str] = OMIT,
        last_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ContactResponse:
        """
        Creates a new Contact object.

        Parameters
        ----------
        phone_number : str
            The contact's phone number in E.164 format.

        first_name : typing.Optional[str]
            The contact's first name.

        last_name : typing.Optional[str]
            The contact's last name.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ContactResponse
            Contact

        Examples
        --------
        import asyncio

        from surge import AsyncSplitit

        client = AsyncSplitit(
            surge_account="YOUR_SURGE_ACCOUNT",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.contacts.create(
                first_name="Dominic",
                last_name="Toretto",
                phone_number="+18015551234",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "contacts",
            method="POST",
            json={
                "first_name": first_name,
                "last_name": last_name,
                "phone_number": phone_number,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ContactResponse,
                    parse_obj_as(
                        type_=ContactResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def show(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ContactResponse:
        """
        Retrieves a Contact object.

        Parameters
        ----------
        id : str


        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ContactResponse
            Contact

        Examples
        --------
        import asyncio

        from surge import AsyncSplitit

        client = AsyncSplitit(
            surge_account="YOUR_SURGE_ACCOUNT",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.contacts.show(
                id="ctc_01j9dy8mdzfn3r0e8x1tbdrdrf",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"contacts/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ContactResponse,
                    parse_obj_as(
                        type_=ContactResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def update(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> ContactResponse:
        """
        Updates the specified contact by setting the values of the parameters passed. Any parameters not provided will be left unchanged.

        Parameters
        ----------
        id : str


        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ContactResponse
            Contact

        Examples
        --------
        import asyncio

        from surge import AsyncSplitit

        client = AsyncSplitit(
            surge_account="YOUR_SURGE_ACCOUNT",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.contacts.update(
                id="ctc_01j9dy8mdzfn3r0e8x1tbdrdrf",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"contacts/{jsonable_encoder(id)}",
            method="PUT",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    ContactResponse,
                    parse_obj_as(
                        type_=ContactResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
