# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.user_response import UserResponse
from ..core.pydantic_utilities import parse_obj_as
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..core.jsonable_encoder import jsonable_encoder
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class UsersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create(
        self,
        *,
        first_name: str,
        last_name: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        photo_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UserResponse:
        """
        Creates a new User object.

        Parameters
        ----------
        first_name : str
            The user's first name.

        last_name : typing.Optional[str]
            The user's last name.

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Set of key-value pairs that will be stored with the user.

        photo_url : typing.Optional[str]
            URL of a photo to be used as the user's avatar.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserResponse
            User

        Examples
        --------
        from surge import Splitit

        client = Splitit(
            surge_account="YOUR_SURGE_ACCOUNT",
            token="YOUR_TOKEN",
        )
        client.users.create(
            first_name="Brian",
            last_name="O'Conner",
            metadata={"email": "boconner@toretti.family", "user_id": 1234},
            photo_url="https://toretti.family/people/brian.jpg",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "users",
            method="POST",
            json={
                "first_name": first_name,
                "last_name": last_name,
                "metadata": metadata,
                "photo_url": photo_url,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    UserResponse,
                    parse_obj_as(
                        type_=UserResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def show(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> UserResponse:
        """
        Retrieves a User object.

        Parameters
        ----------
        id : str


        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserResponse
            User

        Examples
        --------
        from surge import Splitit

        client = Splitit(
            surge_account="YOUR_SURGE_ACCOUNT",
            token="YOUR_TOKEN",
        )
        client.users.show(
            id="usr_01j9dwavghe1ttppewekjjkfrx",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"users/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    UserResponse,
                    parse_obj_as(
                        type_=UserResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncUsersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create(
        self,
        *,
        first_name: str,
        last_name: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        photo_url: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> UserResponse:
        """
        Creates a new User object.

        Parameters
        ----------
        first_name : str
            The user's first name.

        last_name : typing.Optional[str]
            The user's last name.

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]
            Set of key-value pairs that will be stored with the user.

        photo_url : typing.Optional[str]
            URL of a photo to be used as the user's avatar.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserResponse
            User

        Examples
        --------
        import asyncio

        from surge import AsyncSplitit

        client = AsyncSplitit(
            surge_account="YOUR_SURGE_ACCOUNT",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.users.create(
                first_name="Brian",
                last_name="O'Conner",
                metadata={"email": "boconner@toretti.family", "user_id": 1234},
                photo_url="https://toretti.family/people/brian.jpg",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "users",
            method="POST",
            json={
                "first_name": first_name,
                "last_name": last_name,
                "metadata": metadata,
                "photo_url": photo_url,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    UserResponse,
                    parse_obj_as(
                        type_=UserResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def show(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> UserResponse:
        """
        Retrieves a User object.

        Parameters
        ----------
        id : str


        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        UserResponse
            User

        Examples
        --------
        import asyncio

        from surge import AsyncSplitit

        client = AsyncSplitit(
            surge_account="YOUR_SURGE_ACCOUNT",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.users.show(
                id="usr_01j9dwavghe1ttppewekjjkfrx",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"users/{jsonable_encoder(id)}",
            method="GET",
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    UserResponse,
                    parse_obj_as(
                        type_=UserResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
