# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.verification import Verification
from ..core.pydantic_utilities import parse_obj_as
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..types.verification_check_response import VerificationCheckResponse
from ..core.jsonable_encoder import jsonable_encoder
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class VerificationsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create(self, *, phone_number: str, request_options: typing.Optional[RequestOptions] = None) -> Verification:
        """
        Creates a new Verification and sends the code to the given phone number.

        Parameters
        ----------
        phone_number : str
            The phone number to be verified. In E.164 format.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Verification
            Verification

        Examples
        --------
        from surge import Surge

        client = Surge(
            surge_account="YOUR_SURGE_ACCOUNT",
            token="YOUR_TOKEN",
        )
        client.verifications.create(
            phone_number="+18015551234",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "verifications",
            method="POST",
            json={
                "phone_number": phone_number,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    Verification,
                    parse_obj_as(
                        type_=Verification,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    def check(
        self, id: str, *, code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> VerificationCheckResponse:
        """
        Checks the code against a verification.

        Parameters
        ----------
        id : str


        code : str
            The Verification code that was received.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VerificationCheckResponse
            VerificationCheckResponse

        Examples
        --------
        from surge import Surge

        client = Surge(
            surge_account="YOUR_SURGE_ACCOUNT",
            token="YOUR_TOKEN",
        )
        client.verifications.check(
            id="vfn_01jayh15c2f2xamftg0xpyq1nj",
            code="123456",
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            f"verifications/{jsonable_encoder(id)}/checks",
            method="POST",
            json={
                "code": code,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    VerificationCheckResponse,
                    parse_obj_as(
                        type_=VerificationCheckResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncVerificationsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create(
        self, *, phone_number: str, request_options: typing.Optional[RequestOptions] = None
    ) -> Verification:
        """
        Creates a new Verification and sends the code to the given phone number.

        Parameters
        ----------
        phone_number : str
            The phone number to be verified. In E.164 format.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Verification
            Verification

        Examples
        --------
        import asyncio

        from surge import AsyncSurge

        client = AsyncSurge(
            surge_account="YOUR_SURGE_ACCOUNT",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.verifications.create(
                phone_number="+18015551234",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "verifications",
            method="POST",
            json={
                "phone_number": phone_number,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    Verification,
                    parse_obj_as(
                        type_=Verification,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)

    async def check(
        self, id: str, *, code: str, request_options: typing.Optional[RequestOptions] = None
    ) -> VerificationCheckResponse:
        """
        Checks the code against a verification.

        Parameters
        ----------
        id : str


        code : str
            The Verification code that was received.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VerificationCheckResponse
            VerificationCheckResponse

        Examples
        --------
        import asyncio

        from surge import AsyncSurge

        client = AsyncSurge(
            surge_account="YOUR_SURGE_ACCOUNT",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.verifications.check(
                id="vfn_01jayh15c2f2xamftg0xpyq1nj",
                code="123456",
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            f"verifications/{jsonable_encoder(id)}/checks",
            method="POST",
            json={
                "code": code,
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    VerificationCheckResponse,
                    parse_obj_as(
                        type_=VerificationCheckResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
