# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class AttachmentResponse(UniversalBaseModel):
    """
    Response schema for single attachment
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the object.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of attachment.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL of the attachment.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
