# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class ContactResponse(UniversalBaseModel):
    """
    Response schema for single contact
    """

    first_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The contact's first name.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the object.
    """

    last_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The contact's last name.
    """

    phone_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    The contact's phone number in E.164 format.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
