# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
from .contact import Contact
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class Conversation(UniversalBaseModel):
    """
    A conversation with a Contact
    """

    contact: Contact
    id: str = pydantic.Field()
    """
    Unique identifier for the object.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
