# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .message_conversation_contact_params import MessageConversationContactParams
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class MessageConversationParams(UniversalBaseModel):
    """
    Params for selecting or creating a new conversation. Either the id or the Contact must be given.
    """

    contact: typing.Optional[MessageConversationContactParams] = None
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the object.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
