# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class MessageConversationContactParams(UniversalBaseModel):
    """
    Params for selecting or creating a new contact for sending a message. Either the id or the phone number must be given.
    """

    first_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The contact's first name in case a new contact is created.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique identifier for an existing contact.
    """

    last_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The message's last name in case a new contact is created.
    """

    phone_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    The contact's phone number in E.164 format.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
