# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .attachment_response import AttachmentResponse
import pydantic
from .conversation import Conversation
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class MessageResponse(UniversalBaseModel):
    """
    Response schema for single message
    """

    attachments: typing.Optional[typing.List[AttachmentResponse]] = None
    body: typing.Optional[str] = pydantic.Field(default=None)
    """
    The message body.
    """

    conversation: typing.Optional[Conversation] = None
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the object.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
