# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class UserResponse(UniversalBaseModel):
    """
    Response schema for single user
    """

    first_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The user's first name.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique identifier for the object.
    """

    last_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The user's last name.
    """

    metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Set of key-value pairs that will be stored with the user.
    """

    photo_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    URL of a photo to be used as the user's avatar.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
