# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import typing
from .verification_check_response_result import VerificationCheckResponseResult
import pydantic
from .verification import Verification
from ..core.pydantic_utilities import IS_PYDANTIC_V2


class VerificationCheckResponse(UniversalBaseModel):
    """
    The response returned from checking a Verification code
    """

    result: typing.Optional[VerificationCheckResponseResult] = pydantic.Field(default=None)
    """
    The result of the code check.
    """

    verification: typing.Optional[Verification] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
