# This file was auto-generated by Fern from our API Definition.

from ..core.pydantic_utilities import UniversalBaseModel
import pydantic
from .verification_status import VerificationStatus
from ..core.pydantic_utilities import IS_PYDANTIC_V2
import typing


class Verification(UniversalBaseModel):
    """
    A phone number verification
    """

    attempt_count: int = pydantic.Field()
    """
    The number of times the code has been attempted.
    """

    id: str = pydantic.Field()
    """
    Unique identifier for the object.
    """

    phone_number: str = pydantic.Field()
    """
    The phone number being verified. In E.164 format.
    """

    status: VerificationStatus = pydantic.Field()
    """
    The current status of the verification.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
