# This file was auto-generated by Fern from our API Definition.

import typing
from ..core.client_wrapper import SyncClientWrapper
from ..types.message_conversation_params import MessageConversationParams
from ..types.attachment_params import AttachmentParams
from ..core.request_options import RequestOptions
from ..types.message_response import MessageResponse
from ..core.serialization import convert_and_respect_annotation_metadata
from ..core.pydantic_utilities import parse_obj_as
from json.decoder import JSONDecodeError
from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class MessagesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def create(
        self,
        *,
        conversation: MessageConversationParams,
        attachments: typing.Optional[typing.Sequence[AttachmentParams]] = OMIT,
        body: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MessageResponse:
        """
        Sends a Message.

        Parameters
        ----------
        conversation : MessageConversationParams

        attachments : typing.Optional[typing.Sequence[AttachmentParams]]

        body : typing.Optional[str]
            The message body.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Contact

        Examples
        --------
        from surge import (
            AttachmentParams,
            MessageConversationContactParams,
            MessageConversationParams,
            Surge,
        )

        client = Surge(
            surge_account="YOUR_SURGE_ACCOUNT",
            token="YOUR_TOKEN",
        )
        client.messages.create(
            attachments=[
                AttachmentParams(
                    url="https://toretto.family/coronas.gif",
                )
            ],
            body="Thought you could leave without saying goodbye?",
            conversation=MessageConversationParams(
                contact=MessageConversationContactParams(
                    first_name="Dominic",
                    id="ctc_01j9dy8mdzfn3r0e8x1tbdrdrf",
                    last_name="Toretto",
                    phone_number="+18015551234",
                ),
                id="cnv_01j9e0dgmdfkj86c877ws0znae",
            ),
        )
        """
        _response = self._client_wrapper.httpx_client.request(
            "messages",
            method="POST",
            json={
                "attachments": convert_and_respect_annotation_metadata(
                    object_=attachments, annotation=typing.Sequence[AttachmentParams], direction="write"
                ),
                "body": body,
                "conversation": convert_and_respect_annotation_metadata(
                    object_=conversation, annotation=MessageConversationParams, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MessageResponse,
                    parse_obj_as(
                        type_=MessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)


class AsyncMessagesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def create(
        self,
        *,
        conversation: MessageConversationParams,
        attachments: typing.Optional[typing.Sequence[AttachmentParams]] = OMIT,
        body: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MessageResponse:
        """
        Sends a Message.

        Parameters
        ----------
        conversation : MessageConversationParams

        attachments : typing.Optional[typing.Sequence[AttachmentParams]]

        body : typing.Optional[str]
            The message body.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessageResponse
            Contact

        Examples
        --------
        import asyncio

        from surge import (
            AsyncSurge,
            AttachmentParams,
            MessageConversationContactParams,
            MessageConversationParams,
        )

        client = AsyncSurge(
            surge_account="YOUR_SURGE_ACCOUNT",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.messages.create(
                attachments=[
                    AttachmentParams(
                        url="https://toretto.family/coronas.gif",
                    )
                ],
                body="Thought you could leave without saying goodbye?",
                conversation=MessageConversationParams(
                    contact=MessageConversationContactParams(
                        first_name="Dominic",
                        id="ctc_01j9dy8mdzfn3r0e8x1tbdrdrf",
                        last_name="Toretto",
                        phone_number="+18015551234",
                    ),
                    id="cnv_01j9e0dgmdfkj86c877ws0znae",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._client_wrapper.httpx_client.request(
            "messages",
            method="POST",
            json={
                "attachments": convert_and_respect_annotation_metadata(
                    object_=attachments, annotation=typing.Sequence[AttachmentParams], direction="write"
                ),
                "body": body,
                "conversation": convert_and_respect_annotation_metadata(
                    object_=conversation, annotation=MessageConversationParams, direction="write"
                ),
            },
            headers={
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                return typing.cast(
                    MessageResponse,
                    parse_obj_as(
                        type_=MessageResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, body=_response.text)
        raise ApiError(status_code=_response.status_code, body=_response_json)
